version: '3.8'

services:
  backend:
    build:
      context: ./rawFood
      dockerfile: Dockerfile.backend
    command: >
      sh -c "python3 manage.py migrate &&
             python3 manage.py runserver 0.0.0.0:8000"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
    ports: 
      - "8000:8000"
    volumes: 
      - ./rawFood:/app
    depends_on:
      db:
        condition: service_healthy
    restart: always
   

  frontend:
    build:
      context: ./rawFood/frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    volumes:
      - ./rawFood/frontend:/app/frontend
    restart: always

  db:
    image: postgres:13
    ports:
      - '5432:5432'
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: "pg_isready -h db -U postgres"
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
