# Generated by Django 4.2.2 on 2023-07-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Protein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(default='', max_length=16)),
                ('item', models.CharField(default='', max_length=16)),
                ('totalMeat', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('totalOrgan', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('totalBone', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
            ],
        ),
    ]
