# Generated by Django 4.2.2 on 2023-08-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_animal_fk_image_animal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ratio',
            name='bone',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='meat',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='ratio',
            name='organ',
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=7),
        ),
    ]
